
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class consumerloanassistantproject extends javax.swing.JFrame {
    private Object ComputePayment;
    double loan;
    double interest;
    double month;
    double Payment;
    double MonthlyPayment;
    private boolean ComputeButton;
    private double Interest;

  
  

    
    public consumerloanassistantproject() {
        initComponents();
        //XmonthButton.doClick();
        AnalysisButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        balanceField = new javax.swing.JTextField();
        InterestField = new javax.swing.JTextField();
        PaymentField = new javax.swing.JTextField();
        MonthField = new javax.swing.JTextField();
        ComputButton = new javax.swing.JButton();
        AnalysisButton = new javax.swing.JButton();
        xPaymentButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAera = new javax.swing.JTextArea();
        ExitButton = new javax.swing.JButton();
        xMonthPayment = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("loan asssitant");
        setResizable(false);

        jLabel1.setText("Loan Balance");

        jLabel2.setText("Interest Rate");

        jLabel3.setText("Number of Payment");

        jLabel4.setText("Monthly payment");

        balanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceFieldActionPerformed(evt);
            }
        });

        PaymentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentFieldActionPerformed(evt);
            }
        });

        ComputButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ComputButton.setText("Compute Monthly Payment");
        ComputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputButtonActionPerformed(evt);
            }
        });

        AnalysisButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AnalysisButton.setText("New Loan Analysis");
        AnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisButtonActionPerformed(evt);
            }
        });

        xPaymentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xPaymentButton.setText("X");
        xPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPaymentButtonActionPerformed(evt);
            }
        });

        textAera.setColumns(20);
        textAera.setRows(5);
        jScrollPane1.setViewportView(textAera);

        ExitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        xMonthPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xMonthPayment.setText("X");
        xMonthPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xMonthPaymentActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Loan Analysis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InterestField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(xPaymentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(xMonthPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(ComputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(AnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255)
                        .addComponent(ExitButton)))
                .addContainerGap(696, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceField))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InterestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xPaymentButton))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xMonthPayment))
                .addGap(36, 36, 36)
                .addComponent(ComputButton)
                .addGap(30, 30, 30)
                .addComponent(AnalysisButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExitButton)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaymentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentFieldActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
     System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisButtonActionPerformed
        balanceField.setText("");
        InterestField.setText("");
        PaymentField.setText("");
        textAera.setText("");
        AnalysisButton.setEnabled(false);
        ComputButton.setEnabled(true);
        
    }//GEN-LAST:event_AnalysisButtonActionPerformed

    private void xPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPaymentButtonActionPerformed
       ComputePayment=true;
       xPaymentButton.setVisible(false);
       xMonthPayment.setVisible(true);
       MonthField.setEditable(true);
       MonthField.setBackground(Color.WHITE);
       MonthField.setFocusable(true);
       PaymentField.setEditable(false);
       PaymentField.setBackground(Color.YELLOW);
       PaymentField.setFocusable(false);
       balanceField.requestFocus();  
       
    }//GEN-LAST:event_xPaymentButtonActionPerformed

    private void ComputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputButtonActionPerformed
    String iMonthPayment = String.format(MonthField.getText());
    if(balanceField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter amount of Loan",
        "Loan system",JOptionPane.INFORMATION_MESSAGE);
        
    }else{
       loan= Double.parseDouble(balanceField.getText());
       String iBalance = String.format(balanceField.getText());
       
       
    }
    if(InterestField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter amount of Interest",
        "Loan system",JOptionPane.INFORMATION_MESSAGE);
        
    }else{
       interest = Double.parseDouble(InterestField.getText());
       String iInterest = String.format(InterestField.getText());
       
       
    }
    if(PaymentField.getText().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter payment of Number  ",
        "Loan system",JOptionPane.INFORMATION_MESSAGE);
        
    }else{
       Payment = Double.parseDouble(PaymentField.getText());
       String iPayment = String.format(PaymentField.getText());
       
       
    }
  
     

      Payment =  loan +((loan * interest )/100);
     
     
           MonthlyPayment = Payment / 12;
      
      String PayMonth = String.format("%.2f",MonthlyPayment);
       MonthField.setText(PayMonth);
       textAera.append(" \t\n  Consumer loan assistant:\n\n"
                       
                     + " Amount of Loan:\t\t $"+ loan +
                                "\n Number of Payment:\t\t $"+ interest+
                                "\nMonthly Payment:\t\t $" + month+ 
                                 "\nPayment Per Month:\t\t $" +MonthlyPayment+ 
                                 "\nTotal Loan Payment:\t\t $" +Payment+ 
                                  "\n\n Consumer Loan Assistant");
        AnalysisButton.setEnabled(true);
       ComputButton.setEnabled(false);
        
    }//GEN-LAST:event_ComputButtonActionPerformed

    private void balanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceFieldActionPerformed

    private void xMonthPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xMonthPaymentActionPerformed
       // ComputePayment= false;
        xPaymentButton.setVisible(true);
        xMonthPayment.setVisible(false);
        MonthField.setEditable(false);
        MonthField.setBackground(Color.YELLOW);
        MonthField.setFocusable(false);
        PaymentField.setEditable(true);
        PaymentField.setBackground(Color.WHITE);
        PaymentField.setFocusable(true);
        balanceField.requestFocus();
        ComputButton.setVisible(true);
    }//GEN-LAST:event_xMonthPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consumerloanassistantproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consumerloanassistantproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consumerloanassistantproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consumerloanassistantproject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consumerloanassistantproject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalysisButton;
    private javax.swing.JButton ComputButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField InterestField;
    private javax.swing.JTextField MonthField;
    private javax.swing.JTextField PaymentField;
    private javax.swing.JTextField balanceField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAera;
    private javax.swing.JButton xMonthPayment;
    private javax.swing.JButton xPaymentButton;
    // End of variables declaration//GEN-END:variables

    private static class color {

        public color() {
           
        }
    }

    private static class MonthField {

        public MonthField() {
        }
    }

    
}
